name: CI pipeline
on:
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile"
      - "vulnerable-flask-app.py"
jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checkout
        uses: actions/checkout@v2  # Utiliser la version 2
        with:
          ref: ${{ github.ref }}
          repository: phenix19/devsecopslab
          token: ${{ secrets.GITLEAKS }}
      
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install semgrep
          if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image from Dockerfile
        run: |
          docker build -t test_${{ github.run_number }}:v1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1  # Utiliser la version 1
        with:
          username: phenix19
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker tag test_${{ github.run_number }}:v1 phenix19/devsecopslab:v${{ github.run_number }}
          docker push phenix19/devsecopslab:v${{ github.run_number }}

      - name: Set up YQ command
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq

      - name: Edit manifests in ENV repo
        run: |
          yq eval -i '.spec.template.spec.containers[0].image = "phenix19/devsecopslab:v${{ github.run_number }}"' ./kubernetes/deployment.yaml

      - name: Commit and Push to ENV repo
        run: |
          git config  user.email "madreldieny@gmail.com"
          git config  user.name "phenix19"
          git commit -a -m 'Env file is updated with the new image ${{ github.ref }}'
          git push

